# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "uriza86"
client_id = "0b376d2bcd58773b94b72619a1fe54c3"
application_url = "https://table-helen-replaced-via.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://table-helen-replaced-via.trycloudflare.com/auth/callback",
  "https://table-helen-replaced-via.trycloudflare.com/auth/shopify/callback",
  "https://table-helen-replaced-via.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-04367f32.myshopify.com"
